export const pieces = [
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 0,
        y: 1,
        number: 1,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 1,
        y: 1,
        number: 2,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 2,
        y: 1,
        number: 3,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 3,
        y: 1,
        number: 4,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 4,
        y: 1,
        number: 4,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 5,
        y: 1,
        number: 4,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 6,
        y: 1,
        number: 4,
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 7,
        y: 1,
        number: 4,
    },

    {
        piece: "king",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Chess_klt60.png",
        x: 3,
        y: 0,
        number: 4,
    },
    {
        piece: "tower",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chess_rlt60.png",
        x: 7,
        y: 0,
        number: 4,
    },
    {
        piece: "tower",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chess_rlt60.png",
        x: 0,
        y: 0,
        number: 4,
    },
    {
        piece: "queen",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Chess_qlt60.png",
        x: 4,
        y: 0,
        number: 4,
    },
    {
        piece: "bishop",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Chess_blt60.png",
        x: 2,
        y: 0,
        number: 4,
    },
    {
        piece: "bishop",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Chess_blt60.png",
        x: 5,
        y: 0,
        number: 4,
    },
    {
        piece: "horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Chess_nlt60.png",
        x: 6,
        y: 0,
        number: 4,
    },
    {
        piece: "horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Chess_nlt60.png",
        x: 1,
        y: 0,
        number: 4,
    },
]