export const pieces = [
    /*{
        
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 0,
        y: 1,
        color: "white",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 1,
        y: 1,
        color: "white",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 2,
        y: 1,
        color: "white",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 3,
        y: 1,
        color: "white",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 4,
        y: 1,
        color: "white",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 5,
        y: 1,
        color: "white",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 6,
        y: 1,
        color: "white",
    },
    
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Chess_plt60.png",
        x: 7,
        y: 1,
        color: "white",
    },
*/
    {
        piece: "king",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Chess_klt60.png",
        x: 3,
        y: 0,
        color: "white",
    },
    {
        piece: "tower",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chess_rlt60.png",
        x: 7,
        y: 0,
        color: "white",
    },
    {
        piece: "tower",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Chess_rlt60.png",
        x: 0,
        y: 0,
        color: "white",
    },
    {
        piece: "queen",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Chess_qlt60.png",
        x: 4,
        y: 0,
        color: "white",
    },
    {
        piece: "bishop",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Chess_blt60.png",
        x: 2,
        y: 0,
        color: "white",
    },
    {
        piece: "bishop",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Chess_blt60.png",
        x: 5,
        y: 0,
        color: "white",
    },
    {
        piece: "horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Chess_nlt60.png",
        x: 6,
        y: 0,
        color: "white",
    },
    {
        piece: "horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Chess_nlt60.png",
        x: 1,
        y: 0,
        color: "white",
    },
    /*
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 0,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 1,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 2,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 3,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 4,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 5,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 6,
        y: 6,
        color: "black",
    },
    {
        piece: "pawn",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Chess_pdt60.png",
        x: 7,
        y: 6,
        color: "black",
    },
 */
    {
        piece: "king",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Chess_kdt60.png",
        x: 3,
        y: 7,
        color: "black",
    },
    {
        piece: "tower",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Chess_rdt60.png",
        x: 7,
        y: 7,
        color: "black",
    },
    {
        piece: "tower",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Chess_rdt60.png",
        x: 0,
        y: 7,
        color: "white",
    },
    {
        piece: "queen",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/af/Chess_qdt60.png",
        x: 4,
        y: 7,
        color: "black",
    },
    {
        piece: "bishop",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Chess_bdt60.png",
        x: 2,
        y: 7,
        color: "black",
    },
    {
        piece: "bishop",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/81/Chess_bdt60.png",
        x: 5,
        y: 7,
        color: "black",
    },
    {
        piece: "horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Chess_ndt60.png",
        x: 6,
        y: 7,
        color: "black",
    },
    {
        piece: "horse",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Chess_ndt60.png",
        x: 1,
        y: 7,
        color: "black",
    },
]